/***************************************************************************
	Author: ShonK
	Project: Kauai
	Copyright (c) Microsoft Corporation

	Chunky help exporting. Only one API is exported by this module. It
	writes chomp source for the help topics contained in a chunky file.

***************************************************************************/
#ifndef CHELPEXP_H
#define CHELPEXP_H

bool FExportHelpText(PCFL pcfl, PMSNK pmsnk);

#endif //!CHELPEXP_H

