/***************************************************************************
	Author: ShonK
	Project: Kauai
	Reviewed:
	Copyright (c) Microsoft Corporation

	Declarations related to key handling

***************************************************************************/
#ifndef KEYS_H
#define KEYS_H

#define vkNil 0

#define kvkLeft		MacWin(0x1C, VK_LEFT)
#define kvkRight	MacWin(0x1D, VK_RIGHT)
#define kvkUp		MacWin(0x1E, VK_UP)
#define kvkDown		MacWin(0x1F, VK_DOWN)
#define kvkHome		MacWin(0x01, VK_HOME)
#define kvkEnd		MacWin(0x04, VK_END)
#define kvkPageUp	MacWin(0x0B, VK_PRIOR)
#define kvkPageDown	MacWin(0x0C, VK_NEXT)

#define kvkBack		MacWin(0x08, VK_BACK)
#define kvkDelete	MacWin(0x7F, VK_DELETE)
#define kvkReturn	MacWin(0x0D, VK_RETURN)

#endif //!KEYS_H

