/***************************************************************************
	Author: ShonK
	Project: Kauai
	Reviewed:
	Copyright (c) Microsoft Corporation

	Standard KidFrame header file.

***************************************************************************/
#ifndef KIDFRAME_H
#define KIDFRAME_H

#include "frame.h"
#include "kiddef.h"

// forward declarations
typedef class WOKS *PWOKS;
typedef class SCEG *PSCEG;
typedef class GOK *PGOK;
typedef class HBAL *PHBAL;
typedef struct HTOP *PHTOP;


#include "scrcomg.h"
#include "kidworld.h"
#include "screxeg.h"
#include "kidspace.h"
#include "kidhelp.h"

#endif //!KIDFRAME_H
