//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by FT.RC
//
#define cidTestSuite                    40001
#define cidNewTestWnd                   40002
#define cidTextTestWnd                  40004
#define cidStartRecording               40005
#define cidStartPlaying                 40006
#define cidTimeFrameRc                  40007
#define cidTestFni                      40008
#define cidTestPerspective              40009
#define cidTestPictures                 40010
#define cidSetColor                     40011
#define cidSetGrayScale                 40012
#define cidSetDepth1                    40013
#define cidSetDepth2                    40014
#define cidSetDepth4                    40015
#define cidSetDepth8                    40016
#define cidSetDepth16                   40017
#define cidSetDepth32                   40018
#define cidTestFastUpdate               40019
#define cidTestTextEdit                 40020
#define cidTestMbmps                    40021

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40022
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
