/*******************************************************************
 *
 * socres.h
 *
 * Copyright (C) Microsoft Corporation 1993.
 * All Rights reserved.
 *
 *
 * Description: Include file for application product id info
 *
 ******************************************************************/

//
// RCDATA blocks
//
#define RC_PID_NUMBER           128     // NNNNNSSSXXXXXXX\0
#define RCDATA					10

